# -*- coding: utf-8 -*-
"""topsis_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n8OdBOcFBDDUSiIU4FQ4fUiPXaTl-7nr
"""

from google.colab import drive
drive.mount('/content/drive')

import os

base = "/content/drive/MyDrive/TopsisProject"
os.makedirs(base, exist_ok=True)

os.chdir(base)
print(os.getcwd())

import pandas as pd

df = pd.read_excel("/content/data.xlsx")

df.head()

df.to_csv("data.csv", index=False)

print("Converted to data.csv")

code = '''
import sys
import pandas as pd
import numpy as np


def main():

    if len(sys.argv) != 5:
        print("Usage: python topsis.py input.csv weights impacts output.csv")
        return

    file = sys.argv[1]
    weights = sys.argv[2]
    impacts = sys.argv[3]
    output = sys.argv[4]

    try:
        df = pd.read_csv(file)
    except:
        print("File not found")
        return

    if df.shape[1] < 3:
        print("Need at least 3 columns")
        return

    data = df.iloc[:, 1:].values

    try:
        data = data.astype(float)
    except:
        print("Columns must be numeric")
        return

    weights = list(map(float, weights.split(",")))
    impacts = impacts.split(",")

    if len(weights) != data.shape[1]:
        print("Wrong weights")
        return

    if len(impacts) != data.shape[1]:
        print("Wrong impacts")
        return

    for i in impacts:
        if i not in ['+', '-']:
            print("Impacts must be + or -")
            return

    norm = np.sqrt((data ** 2).sum(axis=0))
    data = data / norm

    data = data * weights

    best = []
    worst = []

    for i in range(len(impacts)):
        if impacts[i] == '+':
            best.append(data[:, i].max())
            worst.append(data[:, i].min())
        else:
            best.append(data[:, i].min())
            worst.append(data[:, i].max())

    best = np.array(best)
    worst = np.array(worst)

    d1 = np.sqrt(((data - best) ** 2).sum(axis=1))
    d2 = np.sqrt(((data - worst) ** 2).sum(axis=1))

    score = d2 / (d1 + d2)

    df["Topsis Score"] = score
    df["Rank"] = df["Topsis Score"].rank(ascending=False)

    df.to_csv(output, index=False)

    print("Saved in", output)


if __name__ == "__main__":
    main()
'''

with open("topsis.py","w") as f:
    f.write(code)

print("topsis.py created")

df = pd.read_csv("data.csv")
print(df.shape)
print(df.columns)

!python topsis.py data.csv 1,1,1,1,1 +,+,+,+,+ result.csv

pd.read_csv("result.csv").head()

import os

os.makedirs("topsis_pkg/mytopsis", exist_ok=True)

open("topsis_pkg/mytopsis/__init__.py","w").close()

print("Folders created")

with open("topsis.py") as f:
    code = f.read()

code = code.replace(
    'if __name__ == "__main__":\n    main()',
    'def run():\n    main()'
)

with open("topsis_pkg/mytopsis/main.py","w") as f:
    f.write(code)

print("main.py created")

setup = '''
from setuptools import setup, find_packages

setup(
    name="topsis-aishlee-102316083",
    version="0.2",
    packages=find_packages(),
    author="Aishlee Joshi",
    author_email="ajoshi1_be23@thapar.edu",
    description="TOPSIS Implementation",
    install_requires=["numpy","pandas"],
    entry_points={
        "console_scripts":[
            "topsis=mytopsis.main:run"
        ]
    }
)
'''

with open("setup.py","w") as f:
    f.write(setup)

print("setup.py updated correctly")

!rm -rf build dist *.egg-info
print("Old builds removed")

readme = '''
# Topsis Package

Install:
pip install Topsis-Aishlee-102316083

Run:
topsis data.csv 1,1,1,1,1 +,+,+,+,+ result.csv
'''

with open("topsis_pkg/README.md","w") as f:
    f.write(readme)

print("README created")

!pip install setuptools wheel twine

# Commented out IPython magic to ensure Python compatibility.
# %cd topsis_pkg

!ls

!python setup.py sdist bdist_wheel

!twine upload --username __token__ --password pypi-AgEIcHlwaS5vcmcCJGExNzE3ZDdmLTdkNjMtNGQ1Zi05YjhlLTY0MGI5YTc2YWRlMQACKlszLCIxNWFmZDc5Yi05MzdhLTRkMGMtYTAzOS02Y2FiZDk5MDdhNmQiXQAABiBCN9NTpdXEU-QRb3y3IZw7FHuozbTcllxifCY32sc1IA dist/*

!pwd
!ls

!rm -rf build dist *.egg-info
print("Old builds removed")

!python setup.py sdist bdist_wheel

!ls dist

!twine upload --username __token__ --password pypi-AgEIcHlwaS5vcmcCJGIxNmM3YzhmLTI2YzItNDExZS04MjkzLTZjYTBiMWZmOWQ0MQACKlszLCIxNWFmZDc5Yi05MzdhLTRkMGMtYTAzOS02Y2FiZDk5MDdhNmQiXQAABiBCHYi8HBlzRqb19QwbmyPlA-ruR-DTmSoJ3jD5btHc4w dist/*

!pwd

readme = """
# TOPSIS Assignment

TOPSIS (Technique for Order Preference by Similarity to Ideal Solution) is a multi-criteria decision-making method.

This package provides a command-line implementation of the TOPSIS method in Python. It helps users rank multiple alternatives based on different criteria, weights, and impacts.

## Features
- Accepts CSV input files
- Supports user-defined weights and impacts
- Handles invalid inputs and errors
- Generates ranked output with TOPSIS scores
- Easy to use command-line interface

## Installation
pip install topsis-aishlee-102316083

## Usage
topsis input.csv weights impacts output.csv

Example:
topsis data.csv 1,1,1,1,1 +,+,+,+,+ result.csv

## Author
Aishlee Joshi
"""

with open("README.md", "w") as f:
    f.write(readme)

print("README updated successfully")

setup = '''
from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="topsis-aishlee-102316083",
    version="0.3",
    packages=find_packages(),
    author="Aishlee Joshi",
    author_email="ajoshi1_be23@thapar.edu",
    description="TOPSIS command-line implementation in Python",
    long_description=long_description,
    long_description_content_type="text/markdown",
    install_requires=["numpy","pandas"],
    entry_points={
        "console_scripts":[
            "topsis=mytopsis.main:run"
        ]
    }
)
'''

with open("setup.py","w") as f:
    f.write(setup)

print("setup.py updated with description")

!rm -rf build dist *.egg-info

!python setup.py sdist bdist_wheel

!twine upload --username __token__ --password pypi-AgEIcHlwaS5vcmcCJGIxNmM3YzhmLTI2YzItNDExZS04MjkzLTZjYTBiMWZmOWQ0MQACKlszLCIxNWFmZDc5Yi05MzdhLTRkMGMtYTAzOS02Y2FiZDk5MDdhNmQiXQAABiBCHYi8HBlzRqb19QwbmyPlA-ruR-DTmSoJ3jD5btHc4w dist/*

!pip install flask flask-ngrok pyngrok

import os

os.makedirs("web_app/templates", exist_ok=True)

print("Web app folders created")

html = """
<!DOCTYPE html>
<html>
<head>
    <title>TOPSIS Web App</title>
</head>
<body>

<h2>TOPSIS Decision Making Tool</h2>

<form action="/result" method="post" enctype="multipart/form-data">

    <label>Upload CSV File:</label><br>
    <input type="file" name="file" required><br><br>

    <label>Weights (comma separated):</label><br>
    <input type="text" name="weights" placeholder="1,1,1,1,1" required><br><br>

    <label>Impacts (comma separated):</label><br>
    <input type="text" name="impacts" placeholder="+,+,+,+,+" required><br><br>

    <input type="submit" value="Run TOPSIS">

</form>

</body>
</html>
"""

with open("web_app/templates/index.html","w") as f:
    f.write(html)

print("index.html created")

app_code = """
from flask import Flask, render_template, request, send_file
import pandas as pd
import numpy as np
import os

app = Flask(__name__)


def run_topsis(file, weights, impacts, output):

    df = pd.read_csv(file)
    data = df.iloc[:,1:].values.astype(float)

    weights = list(map(float, weights.split(",")))
    impacts = impacts.split(",")

    norm = np.sqrt((data**2).sum(axis=0))
    data = data / norm

    data = data * weights

    best = []
    worst = []

    for i in range(len(impacts)):
        if impacts[i] == '+':
            best.append(data[:,i].max())
            worst.append(data[:,i].min())
        else:
            best.append(data[:,i].min())
            worst.append(data[:,i].max())

    best = np.array(best)
    worst = np.array(worst)

    d1 = np.sqrt(((data-best)**2).sum(axis=1))
    d2 = np.sqrt(((data-worst)**2).sum(axis=1))

    score = d2/(d1+d2)

    df["Topsis Score"] = score
    df["Rank"] = df["Topsis Score"].rank(ascending=False)

    df.to_csv(output,index=False)


@app.route("/")
def home():
    return render_template("index.html")


@app.route("/result", methods=["POST"])
def result():

    file = request.files["file"]
    weights = request.form["weights"]
    impacts = request.form["impacts"]

    input_file = "uploaded.csv"
    output_file = "result.csv"

    file.save(input_file)

    run_topsis(input_file, weights, impacts, output_file)

    return send_file(output_file, as_attachment=True)


if __name__ == "__main__":
    app.run()
"""

with open("web_app/app.py","w") as f:
    f.write(app_code)

print("app.py created")

# Commented out IPython magic to ensure Python compatibility.
# %cd web_app
!python app.py

!python app.py &

from pyngrok import ngrok

public_url = ngrok.connect(5000)
print("Your Website Link:", public_url)











